import { Translation } from './types';

export const IMAGES = {
  hero: '/assets/toutu.png',
  brandStory: 'https://images.unsplash.com/photo-1507652313519-d4511f7b4ad2?q=80&w=2070&auto=format&fit=crop',
  science: 'https://images.unsplash.com/photo-1579154235602-3c2c2aa5d72e?q=80&w=2070&auto=format&fit=crop',
  scienceBg: 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?q=80&w=2070&auto=format&fit=crop',
  scienceDetail: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?q=80&w=2070&auto=format&fit=crop',
  scienceDetail2: 'https://images.unsplash.com/photo-1532187875605-1ef6c237ddc4?q=80&w=2070&auto=format&fit=crop',
  scienceDetail3: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=2070&auto=format&fit=crop',
  scienceDetail4: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=2070&auto=format&fit=crop',
  product: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=2070&auto=format&fit=crop',
  product1: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=2070&auto=format&fit=crop',
  product2: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=2070&auto=format&fit=crop',
  product3: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=2070&auto=format&fit=crop',
  clinical: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=2070&auto=format&fit=crop',
  factory: '/assets/gongchang.png',
  olympic: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=2070&auto=format&fit=crop',
  aerospace: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2070&auto=format&fit=crop',
  nobel: '/assets/shouyin.png',
  thesis: '/assets/wenxian.png',
  abstract: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=2070&auto=format&fit=crop',
  newsletter: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2070&auto=format&fit=crop',
};

export const TRANSLATIONS: Record<string, Translation> = {
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      science: 'Science',
      authority: 'Authority',
      clinical: 'Clinical',
      factory: 'Factory',
      language: 'Language',
    },
    hero: {
      subtitle: 'The Future of Biological Aging',
      title: 'Redefining the Life Industry',
      titleItalic: 'Forever Great.',
      breakthrough: '2025 Global Breakthrough: Exogenous nucleotide intervention significantly delays epigenetic aging by 3.08 years.',
      cta: 'Anti-Aging | Anti-Wrinkle | Cellular Repair',
      scroll: 'Scroll',
    },
    products: {
      label: 'Product Collection',
      title: 'Precision Formulations for Cellular Longevity.',
      comingSoon: 'Coming Soon',
      mallComingSoon: 'Mall functionality coming soon',
      items: [
        {
          name: "5'NTs® Cellular Reprogramming",
          desc: "Targeting telomeres to reprogram cells to a younger state with advanced nucleotide technology.",
          category: 'Supplement',
          image: '/assets/hgd2.png',
        },
        {
          name: 'Anticare Lifting Concentrate',
          desc: 'Oral PDRN lifting drink that creates a 4D lifting net for deep skin rejuvenation.',
          category: 'Supplement',
          image: '/assets/xz2.png',
        },
        {
          name: 'Crystal Tomato Whitening Supplement',
          desc: 'Luminous whitening tablets featuring white tomato powder and solid hydrogen for radiant skin.',
          category: 'Supplement',
          image: '/assets/fq2.png',
        },
        {
          name: 'Nanobubble Hydrogen Water',
          desc: 'Pure drinking water enriched with nanobubble hydrogen for superior cellular hydration.',
          category: 'Wellness',
          image: '/assets/qs.png',
        },
        {
          name: 'Silk Mask Paper',
          desc: 'Premium silk mask paper specially designed for use with nanobubble hydrogen water.',
          category: 'Skincare',
          image: '/assets/mm.png',
        },
      ],
    },
    science: {
      label: 'Science & Mechanism',
      title: 'Revealing the DNA Damage Mechanism Behind Aging.',
      mechanism: 'The human DNA suffers 19,000 attacks per day on average.',
      seventhNutrient: 'Nucleotides: Acclaimed by academia as the "7th major nutrient" alongside carbohydrates, proteins, fats, etc.',
      items: [
        {
          name: "5'NTs® Technology",
          desc: 'Not only promotes NAD+ synthesis but also directly acts on DNA repair and telomere lengthening.',
        },
        {
          name: 'Yeast Protein',
          desc: 'An efficient ingredient for NAD+ synthesis, currently the only approved microbial protein for food use in China.',
        },
      ],
    },
    authority: {
      label: 'Brand Authority',
      title: 'National-Level Credibility.',
      olympic: 'Guarding the Olympic Legion for 24 years! 13 products selected for the National Team catalog.',
      aerospace: 'Partner of China Aerospace Industry.',
      nobel: 'Supported by handwritten signatures from 26 Nobel Prize winners.',
    },
    clinical: {
      label: 'R&D / Evidence',
      title: 'TALENTs Clinical Study.',
      conclusion: 'Published in Advanced Science (IF 14.3): Confirmed significant improvement in physical fatigue and immune function.',
      summary: 'Over 20 years of research on nucleotide anti-aging functions, from animal experiments to human clinical trials.',
    },
    factory: {
      label: 'Super Factory',
      title: 'Industry Leading Production.',
      description: 'Equipped with global leading RNA production chemical plants and unmanned, fully automated equipment.',
      certifications: ['FDA Registered', 'ISO 22000', 'HACCP', 'GMP+'],
    },
    thesis: {
      title: 'Thesis Center',
      cta: 'Learn More. Gain exclusive access to clinical insights and limited edition releases.',
      items: [
        {
          journal: 'Published in "Nutrients", 2021, Vol. 13, Issue 9',
          summary: 'NTs can successfully establish an aging model by regulating induced oxidative stress.',
        },
        {
          journal: 'Published in "Food Science", 2013, Issue 15',
          summary: 'In-depth discussion on the anti-aging functions of nucleotides and their impact on organisms.',
        },
      ],
    },
    newsletter: {
      title: 'Learn More.',
      desc: 'Start Precision Life Management',
      placeholder: 'Your email address',
      button: 'Subscribe',
    },
    footer: {
      tagline: 'Precision aesthetics for the modern individual. Crafted with scientific rigor.',
      navLabel: 'Navigation',
      infoLabel: 'Information',
      legal: 'Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      copyright: '© 2024 FOOCHY ATELIER. ALL RIGHTS RESERVED.',
    },
  },
  'zh-CN': {
    nav: {
      home: '首页',
      products: '产品系列',
      science: '科学发现',
      authority: '官方背书',
      clinical: '临床研究',
      factory: '超级工厂',
      language: '语言',
    },
    hero: {
      subtitle: '生物衰老的未来',
      title: '让生命产业',
      titleItalic: '永远伟大。',
      breakthrough: '2025全球突破：外源核苷酸干预显著延缓表现遗传学衰老3.08岁。',
      cta: '抗衰 | 抗皱 | 细胞修复',
      scroll: '滚动',
    },
    products: {
      label: '产品系列',
      title: '针对细胞长寿的精准配方。',
      comingSoon: '敬请期待',
      mallComingSoon: '商城功能即将上线',
      items: [
        {
          name: "5'NTs® 靶向端粒胶囊",
          desc: '靶向端粒，重塑细胞，利用先进的5\'NTs核苷酸技术让细胞重返年轻状态。',
          category: '营养补充',
          image: '/assets/hgd2.png',
        },
        {
          name: 'PDRN 四维提拉饮',
          desc: '口服PDRN提拉饮，构建四维提拉网，深度提拉紧致，焕活肌肤。',
          category: '营养补充',
          image: '/assets/xz2.png',
        },
        {
          name: '光感「铂铂片」',
          desc: '口服光感「铂铂片」，蕴含白番茄冻干粉与固态氢，由内而外焕发肌肤光感。',
          category: '营养补充',
          image: '/assets/fq2.png',
        },
        {
          name: '纳米气泡氢型饮用水',
          desc: '纳米气泡氢型饮用水，高浓度氢气，为细胞提供极致补水与代谢支持。',
          category: '健康饮水',
          image: '/assets/qs.png',
        },
        {
          name: '天丝面膜纸',
          desc: '天丝面膜纸，纳米气泡氢水专用，天然柔软贴肤，深度导入营养。',
          category: '专业护肤',
          image: '/assets/mm.png',
        },
      ],
    },
    science: {
      label: '科学机理',
      title: '揭秘衰老背后的DNA损伤机制。',
      mechanism: '人体DNA平均每天要遭受1万9千次攻击。',
      seventhNutrient: '核苷酸：被学术界誉为碳水、蛋白质、脂肪等之外的“第7大营养素”。',
      items: [
        {
          name: "5'NTs® 专利技术",
          desc: '不仅促进NAD+合成，更直接针对DNA修复与端粒延长。',
        },
        {
          name: '酵母蛋白',
          desc: '合成 NAD+ 的高效成分，我国目前唯一获批准的食品用微生物蛋白。',
        },
      ],
    },
    authority: {
      label: '官方背书',
      title: '国家级公信力。',
      olympic: '守护奥运军团24年！13款产品入围国家队集中采购营养食品目录。',
      aerospace: '中国航天事业合作伙伴。',
      nobel: '26位诺贝尔奖得主亲自留下手迹支持。',
    },
    clinical: {
      label: '科研实证',
      title: 'TALENTs临床研究。',
      conclusion: '发表于IF 14.3的《Advanced Science》：证实可显著改善机体疲劳、增强免疫功能。',
      summary: '历经20余年核苷酸抗衰功能研究，从动物实验到人体临床的完整闭环。',
    },
    factory: {
      label: '超级工厂',
      title: '行业领先的品质支撑。',
      description: '拥有全球领先的RNA生产化工厂及无人化、全自动化设备。',
      certifications: ['FDA注册', 'ISO 22000', 'HACCP', 'GMP+'],
    },
    thesis: {
      title: '文献中心',
      cta: '与生命科学专家对话，获取您的专属核苷酸营养方案',
      items: [
        {
          journal: '本论文发布于《Nutrients》杂志2021年第13卷第9期',
          summary: 'NTs可通过调节诱导氧化应激成功建立了衰老模型，有助于拓宽NTs的研究领域。',
        },
        {
          journal: '本论文发布于《食品科学》2013年第15期',
          summary: '深入探讨核苷酸的抗衰老功能及其对生物体的影响。',
        },
      ],
    },
    newsletter: {
      title: '了解更多。',
      desc: '开启精准生命管理',
      placeholder: '您的电子邮件地址',
      button: '订阅',
    },
    footer: {
      tagline: '为现代个人打造的精准美学。以科学的严谨态度精心制作。',
      navLabel: '导航',
      infoLabel: '信息',
      legal: '法律声明',
      privacy: '隐私政策',
      terms: '服务条款',
      copyright: '© 2024 FOOCHY ATELIER. 保留所有权利。',
    },
  },
  'zh-TW': {
    nav: {
      home: '首頁',
      products: '產品系列',
      science: '科學發現',
      authority: '官方背書',
      clinical: '臨床研究',
      factory: '超級工廠',
      language: '語言',
    },
    hero: {
      subtitle: '生物衰老的未來',
      title: '讓生命產業',
      titleItalic: '永遠偉大。',
      breakthrough: '2025全球突破：外源核苷酸干預顯著延緩表現遺傳學衰老3.08歲。',
      cta: '抗衰 | 抗皺 | 細胞修復',
      scroll: '滾動',
    },
    products: {
      label: '產品系列',
      title: '針對細胞長壽的精準配方。',
      comingSoon: '敬請期待',
      mallComingSoon: '商城功能即將上線',
      items: [
        {
          name: "5'NTs® 靶向端粒膠囊",
          desc: '靶向端粒，重塑細胞，利用先進的5\'NTs核苷酸技術讓細胞重返年輕狀態。',
          category: '營養補充',
          image: '/assets/hgd2.png',
        },
        {
          name: 'PDRN 四維提拉飲',
          desc: '口服PDRN提拉飲，構建四維提拉網，深度提拉緊致，煥活肌膚。',
          category: '營養補充',
          image: '/assets/xz2.png',
        },
        {
          name: '光感「鉑鉑片」',
          desc: '口服光感「鉑鉑片」，蘊含白番茄凍乾粉與固態氫，由內而外煥發肌膚光感。',
          category: '營養補充',
          image: '/assets/fq2.png',
        },
        {
          name: '納米氣泡氫型飲用水',
          desc: '納米氣泡氫型飲用水，高濃度氫氣，為細胞提供極致補水與代謝支持。',
          category: '健康飲水',
          image: '/assets/qs.png',
        },
        {
          name: '天絲面膜紙',
          desc: '天絲面膜紙，納米氣泡氫水專用，天然柔軟貼膚，深度導入營養。',
          category: '專業護膚',
          image: '/assets/mm.png',
        },
      ],
    },
    science: {
      label: '科學機理',
      title: '揭秘衰老背後的DNA損傷機制。',
      mechanism: '人體DNA平均每天要遭受1萬9千次攻擊。',
      seventhNutrient: '核苷酸：被學術界譽為碳水、蛋白質、脂肪等之外的「第7大營養素」。',
      items: [
        {
          name: "5'NTs® 專利技術",
          desc: '不僅促進NAD+合成，更直接針對DNA修復與端粒延長。',
        },
        {
          name: '酵母蛋白',
          desc: '合成 NAD+ 的高效成分，我國目前唯一獲批准的食品用微生物蛋白。',
        },
      ],
    },
    authority: {
      label: '官方背書',
      title: '國家級公信力。',
      olympic: '守護奧運軍團24年！13款產品入圍國家隊集中採購營養食品目錄。',
      aerospace: '中國航天事業合作伙伴。',
      nobel: '26位諾貝爾獎得主親自留下手跡支持。',
    },
    clinical: {
      label: '科研實證',
      title: 'TALENTs臨床研究。',
      conclusion: '發表於IF 14.3的《Advanced Science》：證實可顯著改善機體疲勞、增強免疫功能。',
      summary: '歷經20餘年核苷酸抗衰功能研究，從動物實驗到人體臨床的完整閉環。',
    },
    factory: {
      label: '超級工廠',
      title: '行業領先的品質支撐。',
      description: '擁有全球領先的RNA生產化工廠及無人化、全自動化設備。',
      certifications: ['FDA註冊', 'ISO 22000', 'HACCP', 'GMP+'],
    },
    thesis: {
      title: '文獻中心',
      cta: '與生命科學專家對話，獲取您的專屬核苷酸營養方案',
      items: [
        {
          journal: '本論文發布於《Nutrients》雜誌2021年第13卷第9期',
          summary: 'NTs可通過調節誘導氧化應激成功建立了衰老模型，有助於拓寬NTs的研究領域。',
        },
        {
          journal: '本論文發布於《食品科學》2013年第15期',
          summary: '深入探討核苷酸的抗衰老功能及其對生物體的影响。',
        },
      ],
    },
    newsletter: {
      title: '了解更多。',
      desc: '開啟精準生命管理',
      placeholder: '您的電子郵件地址',
      button: '訂閱',
    },
    footer: {
      tagline: '為現代個人打造的精準美學。以科學的嚴謹態度精心製作。',
      navLabel: '導航',
      infoLabel: '信息',
      legal: '法律聲明',
      privacy: '隱私政策',
      terms: '服務條款',
      copyright: '© 2024 FOOCHY ATELIER. 保留所有權利。',
    },
  },
};
